# Generated by Django 5.2.11 on 2026-03-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0004_bikebooking_camerabooking_laptopbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikebooking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bikebooking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bikebooking',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bikebooking',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10),
        ),
        migrations.AddField(
            model_name='camerabooking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='camerabooking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='camerabooking',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camerabooking',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=2500, max_digits=10),
        ),
        migrations.AddField(
            model_name='laptopbooking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='laptopbooking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='laptopbooking',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptopbooking',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bikebooking',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bikebooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='camerabooking',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='camerabooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='laptopbooking',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='laptopbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
    ]
