# Generated by Django 5.2.10 on 2026-03-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0005_bikebooking_email_bikebooking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikebooking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='camerabooking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptopbooking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
