# Generated by Django 5.2.11 on 2026-04-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0006_bikebooking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikebooking',
            name='late_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camerabooking',
            name='late_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laptopbooking',
            name='late_fees',
            field=models.IntegerField(default=0),
        ),
    ]
