# Generated by Django 5.2.10 on 2026-04-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0007_bikebooking_late_fees_camerabooking_late_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikebooking',
            name='damage_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bikebooking',
            name='deposit_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikebooking',
            name='returned_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='camerabooking',
            name='damage_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camerabooking',
            name='deposit_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camerabooking',
            name='returned_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='laptopbooking',
            name='damage_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laptopbooking',
            name='deposit_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laptopbooking',
            name='returned_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
